language: ruby
cache: 
  - bundler: true
  - directories:
    - /home/travis/.rvm/
rvm:
 - 2.1

before_script:
  - bundle exec rake app:server:rails:install_dep
  - bundle exec rake app:server:flack:install
  - bundle exec rake app:server:flack:start

script: bundle exec rspec
