source 'https://rubygems.org'

# ~Standard Rails stack
gem 'rails', '4.2.8'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'

# This is only required in the dummy app, to start flack with `rack server:start`
gem 'flack'

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
end

# Require active-trail gem
gem 'active-trail', path: '../../../'

gem 'statesman'
gem 'statesman-events'
gem 'simple_form', '~> 3.1'